[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"

[server]
maxUploadSize = 200
enableCORS = false
enableWebsocketCompression = false

[browser]
gatherUsageStats = false